{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavTo_ItemEditScreen"
	},
	"PageToOpen": "/ZSSAM2405_SRM/Pages/SRM/PhysicalInventory/PI_Items_EditScreen.page",
	"ContextBinding": "{/}"
}